-- =============================================================================
-- FILE:        Views/01_CMS_Views.sql
-- TAB:         CMS (Content/Customer Management)
-- SOURCE TABLES: ../01_CMS.sql, ../00_Master_Tables.sql
-- SCOPE:       One summary view, one row per client. No chart views -- CMS
--              has no chart in src/chart_generator.py.
--
-- USAGE: views take no parameters (portable ANSI SQL, not an engine-specific
-- parameterized function). The app queries with a WHERE filter, e.g.:
--     SELECT * FROM VW_CMS_SUMMARY WHERE APR_CLIENT_CODE = ?
-- which is why every underlying table already carries a leading index on
-- APR_CLIENT_CODE (see ../00_Master_Tables.sql and ../01_CMS.sql).
--
-- ASSUMPTION: CMS_CUSTOMER_ADDRESS / CMS_CUSTOMER_CONTACT have at most one
-- row per client with IS_PRIMARY='Y' (data-integrity assumption, not
-- enforced by a DB constraint in ../01_CMS.sql). If that assumption is ever
-- violated, this view will silently pick up an arbitrary one of the
-- duplicates via the LEFT JOIN -- worth a CHECK/unique-filtered-index at
-- deployment time if this matters.
-- =============================================================================

CREATE VIEW VW_CMS_SUMMARY AS
SELECT
    CP.APR_CLIENT_CODE,
    CM.CLIENT_NAME,
    CM.CLIENT_SEGMENT,
    CM.CLIENT_STATUS,
    CP.GROUP_NAME,
    CP.PARENT_COMPANY_NAME,
    CP.WEBSITE_URL,
    CP.CREDIT_RATING,
    CP.RATING_AGENCY,
    CP.RATING_DATE,
    CP.RELATIONSHIP_SINCE_DATE,
    CP.ANNUAL_TURNOVER_AMOUNT,
    SEG.SEGMENT_CODE            AS CURRENT_SEGMENT_CODE,
    ADDR.ADDRESS_LINE1          AS PRIMARY_ADDRESS_LINE1,
    ADDR.CITY                   AS PRIMARY_CITY,
    ADDR.STATE                  AS PRIMARY_STATE,
    ADDR.COUNTRY                AS PRIMARY_COUNTRY,
    ADDR.PIN_CODE                AS PRIMARY_PIN_CODE,
    CONT.CONTACT_PERSON_NAME    AS PRIMARY_CONTACT_NAME,
    CONT.DESIGNATION            AS PRIMARY_CONTACT_DESIGNATION,
    CONT.EMAIL                  AS PRIMARY_CONTACT_EMAIL,
    CONT.PHONE_NUMBER           AS PRIMARY_CONTACT_PHONE,
    COALESCE(BAL.TOTAL_CURRENT_BALANCE, 0)  AS TOTAL_CURRENT_BALANCE,
    COALESCE(ACC.ACTIVE_ACCOUNT_COUNT, 0)   AS ACTIVE_ACCOUNT_COUNT,
    COMM.LAST_COMMUNICATION_DATE,
    CL.LAST_CALL_DATE,
    MTG.LAST_MEETING_DATE,
    COALESCE(DOC.DOCUMENT_COUNT, 0)          AS DOCUMENT_COUNT,
    COALESCE(DOC.EXPIRED_DOCUMENT_COUNT, 0)  AS EXPIRED_DOCUMENT_COUNT
FROM CMS_CUSTOMER_PROFILE CP
JOIN CLIENT_MASTER CM
    ON CM.APR_CLIENT_CODE = CP.APR_CLIENT_CODE
LEFT JOIN CMS_CUSTOMER_ADDRESS ADDR
    ON ADDR.APR_CLIENT_CODE = CP.APR_CLIENT_CODE AND ADDR.IS_PRIMARY = 'Y'
LEFT JOIN CMS_CUSTOMER_CONTACT CONT
    ON CONT.APR_CLIENT_CODE = CP.APR_CLIENT_CODE AND CONT.IS_PRIMARY = 'Y'
LEFT JOIN CMS_CUSTOMER_SEGMENT_HISTORY SEG
    ON SEG.APR_CLIENT_CODE = CP.APR_CLIENT_CODE AND SEG.EFFECTIVE_TO_DATE IS NULL
LEFT JOIN (
    SELECT APR_CLIENT_CODE, SUM(CURRENT_BALANCE) AS TOTAL_CURRENT_BALANCE
    FROM CMS_ACCOUNT_BALANCE_CURRENT
    GROUP BY APR_CLIENT_CODE
) BAL ON BAL.APR_CLIENT_CODE = CP.APR_CLIENT_CODE
LEFT JOIN (
    SELECT APR_CLIENT_CODE, COUNT(*) AS ACTIVE_ACCOUNT_COUNT
    FROM ACCOUNT_MASTER
    WHERE ACCOUNT_STATUS = 'Active'
    GROUP BY APR_CLIENT_CODE
) ACC ON ACC.APR_CLIENT_CODE = CP.APR_CLIENT_CODE
LEFT JOIN (
    SELECT APR_CLIENT_CODE, MAX(COMMUNICATION_DATE) AS LAST_COMMUNICATION_DATE
    FROM CMS_COMMUNICATION_LOG
    GROUP BY APR_CLIENT_CODE
) COMM ON COMM.APR_CLIENT_CODE = CP.APR_CLIENT_CODE
LEFT JOIN (
    SELECT APR_CLIENT_CODE, MAX(CALL_DATE) AS LAST_CALL_DATE
    FROM CMS_CALL_LOG
    GROUP BY APR_CLIENT_CODE
) CL ON CL.APR_CLIENT_CODE = CP.APR_CLIENT_CODE
LEFT JOIN (
    SELECT APR_CLIENT_CODE, MAX(MEETING_DATE) AS LAST_MEETING_DATE
    FROM CMS_MEETING_RECORD
    GROUP BY APR_CLIENT_CODE
) MTG ON MTG.APR_CLIENT_CODE = CP.APR_CLIENT_CODE
LEFT JOIN (
    SELECT
        APR_CLIENT_CODE,
        COUNT(*) AS DOCUMENT_COUNT,
        SUM(CASE WHEN DOCUMENT_STATUS = 'Expired' THEN 1 ELSE 0 END) AS EXPIRED_DOCUMENT_COUNT
    FROM CMS_DOCUMENT_REPOSITORY
    GROUP BY APR_CLIENT_CODE
) DOC ON DOC.APR_CLIENT_CODE = CP.APR_CLIENT_CODE;
