-- =============================================================================
-- FILE:        Views/04_Product_Holdings_Views.sql
-- TAB:         Product Holdings
-- SOURCE TABLES: ../04_Product_Holdings.sql, ../00_Master_Tables.sql
-- SCOPE:       One summary view, one row per client. No chart views -- this
--              tab has no chart in src/chart_generator.py.
--
-- USAGE: views take no parameters; the app queries with a WHERE filter, e.g.:
--     SELECT * FROM VW_PRODUCT_HOLDINGS_SUMMARY WHERE APR_CLIENT_CODE = ?
-- =============================================================================

CREATE VIEW VW_PRODUCT_HOLDINGS_SUMMARY AS
WITH LATEST_UTILIZATION AS (
    SELECT HOLDING_ID, UTILIZATION_PERCENTAGE
    FROM (
        SELECT HOLDING_ID, UTILIZATION_PERCENTAGE,
               ROW_NUMBER() OVER (PARTITION BY HOLDING_ID ORDER BY AS_OF_DATE DESC) AS RN
        FROM PRODUCT_UTILIZATION
    ) R
    WHERE R.RN = 1
),
HOLDING_ROLLUP AS (
    SELECT
        PHS.APR_CLIENT_CODE,
        COUNT(CASE WHEN PHS.HOLDING_STATUS = 'Active' THEN 1 END) AS ACTIVE_PRODUCT_COUNT,
        AVG(LU.UTILIZATION_PERCENTAGE) AS AVG_UTILIZATION_PERCENTAGE
    FROM PRODUCT_HOLDING_SUMMARY PHS
    LEFT JOIN LATEST_UTILIZATION LU ON LU.HOLDING_ID = PHS.HOLDING_ID
    GROUP BY PHS.APR_CLIENT_CODE
),
FEE_ROLLUP AS (
    SELECT
        PHS.APR_CLIENT_CODE,
        SUM(FEE.FEE_AMOUNT) AS TOTAL_FEE_INCOME
    FROM PRODUCT_FEE_INCOME FEE
    JOIN PRODUCT_HOLDING_SUMMARY PHS ON PHS.HOLDING_ID = FEE.HOLDING_ID
    GROUP BY PHS.APR_CLIENT_CODE
),
CROSS_SELL_ROLLUP AS (
    SELECT
        APR_CLIENT_CODE,
        COUNT(*) AS OPEN_CROSS_SELL_OPPORTUNITY_COUNT,
        SUM(POTENTIAL_VALUE) AS OPEN_CROSS_SELL_POTENTIAL_VALUE
    FROM PRODUCT_CROSS_SELL_OPPORTUNITY
    WHERE OPPORTUNITY_STATUS = 'Open'
    GROUP BY APR_CLIENT_CODE
),
LATEST_SCORE AS (
    SELECT APR_CLIENT_CODE, RELATIONSHIP_SCORE, RELATIONSHIP_TIER
    FROM (
        SELECT APR_CLIENT_CODE, RELATIONSHIP_SCORE, RELATIONSHIP_TIER,
               ROW_NUMBER() OVER (PARTITION BY APR_CLIENT_CODE ORDER BY AS_OF_DATE DESC) AS RN
        FROM PRODUCT_RELATIONSHIP_DEPTH_SCORE
    ) R
    WHERE R.RN = 1
),
TOP_CHANNEL AS (
    SELECT APR_CLIENT_CODE, CHANNEL_NAME
    FROM (
        SELECT APR_CLIENT_CODE, CHANNEL_NAME,
               ROW_NUMBER() OVER (PARTITION BY APR_CLIENT_CODE ORDER BY USAGE_COUNT DESC) AS RN
        FROM PRODUCT_CHANNEL_USAGE
    ) R
    WHERE R.RN = 1
),
SERVICE_REQUEST_ROLLUP AS (
    SELECT
        APR_CLIENT_CODE,
        COUNT(*) AS OPEN_SERVICE_REQUEST_COUNT
    FROM PRODUCT_SERVICE_REQUEST
    WHERE REQUEST_STATUS <> 'Closed'
    GROUP BY APR_CLIENT_CODE
)
SELECT
    C.APR_CLIENT_CODE,
    COALESCE(HR.ACTIVE_PRODUCT_COUNT, 0) AS ACTIVE_PRODUCT_COUNT,
    HR.AVG_UTILIZATION_PERCENTAGE,
    COALESCE(FR.TOTAL_FEE_INCOME, 0)     AS TOTAL_FEE_INCOME,
    COALESCE(CS.OPEN_CROSS_SELL_OPPORTUNITY_COUNT, 0)   AS OPEN_CROSS_SELL_OPPORTUNITY_COUNT,
    COALESCE(CS.OPEN_CROSS_SELL_POTENTIAL_VALUE, 0)     AS OPEN_CROSS_SELL_POTENTIAL_VALUE,
    LS.RELATIONSHIP_SCORE,
    LS.RELATIONSHIP_TIER,
    TC.CHANNEL_NAME AS TOP_CHANNEL_NAME,
    COALESCE(SR.OPEN_SERVICE_REQUEST_COUNT, 0) AS OPEN_SERVICE_REQUEST_COUNT
FROM CLIENT_MASTER C
LEFT JOIN HOLDING_ROLLUP HR ON HR.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN FEE_ROLLUP FR ON FR.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN CROSS_SELL_ROLLUP CS ON CS.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN LATEST_SCORE LS ON LS.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN TOP_CHANNEL TC ON TC.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN SERVICE_REQUEST_ROLLUP SR ON SR.APR_CLIENT_CODE = C.APR_CLIENT_CODE;
