-- =============================================================================
-- FILE:        Views/05_RM_Details_Interactions_Views.sql
-- TAB:         RM Details & Interactions
-- SOURCE TABLES: ../05_RM_Details_Interactions.sql, ../00_Master_Tables.sql,
--              ../01_CMS.sql is NOT queried directly here -- RM_INTERACTION_
--              SUMMARY is already the pre-aggregated rollup of CMS's raw logs
--              (see ../05_RM_Details_Interactions.sql header).
-- SCOPE:       One summary view, one row per client. No chart views -- this
--              tab has no chart in src/chart_generator.py.
--
-- USAGE: views take no parameters; the app queries with a WHERE filter, e.g.:
--     SELECT * FROM VW_RM_DETAILS_SUMMARY WHERE APR_CLIENT_CODE = ?
--
-- ASSUMPTION: CLIENT_RM_MAPPING has at most one row per client with
-- MAPPING_END_DATE IS NULL AND IS_PRIMARY='Y' (data-integrity assumption,
-- not enforced by a DB constraint in ../00_Master_Tables.sql).
-- =============================================================================

CREATE VIEW VW_RM_DETAILS_SUMMARY AS
WITH CURRENT_MAPPING AS (
    SELECT APR_CLIENT_CODE, RM_CODE
    FROM CLIENT_RM_MAPPING
    WHERE MAPPING_END_DATE IS NULL AND IS_PRIMARY = 'Y'
),
LATEST_INTERACTION AS (
    SELECT APR_CLIENT_CODE, TOTAL_CALLS_COUNT, TOTAL_MEETINGS_COUNT, TOTAL_EMAILS_COUNT, LAST_INTERACTION_DATE
    FROM (
        SELECT APR_CLIENT_CODE, TOTAL_CALLS_COUNT, TOTAL_MEETINGS_COUNT, TOTAL_EMAILS_COUNT, LAST_INTERACTION_DATE,
               ROW_NUMBER() OVER (PARTITION BY APR_CLIENT_CODE ORDER BY PERIOD_END_DATE DESC) AS RN
        FROM RM_INTERACTION_SUMMARY
    ) R
    WHERE R.RN = 1
),
ESCALATION_ROLLUP AS (
    SELECT APR_CLIENT_CODE, COUNT(*) AS OPEN_ESCALATION_COUNT
    FROM RM_ESCALATION_LOG
    WHERE RESOLUTION_STATUS = 'Open'
    GROUP BY APR_CLIENT_CODE
),
VISIT_ROLLUP AS (
    SELECT APR_CLIENT_CODE, MIN(PLANNED_DATE) AS NEXT_PLANNED_VISIT_DATE
    FROM RM_CLIENT_VISIT_PLAN
    WHERE VISIT_STATUS = 'Planned' AND PLANNED_DATE >= CURRENT_DATE
    GROUP BY APR_CLIENT_CODE
),
FEEDBACK_ROLLUP AS (
    SELECT APR_CLIENT_CODE, AVG(RATING) AS AVERAGE_FEEDBACK_RATING
    FROM RM_CLIENT_FEEDBACK
    GROUP BY APR_CLIENT_CODE
)
SELECT
    C.APR_CLIENT_CODE,
    CM.RM_CODE,
    RM.RM_NAME,
    RM.DESIGNATION,
    RM.EMAIL AS RM_EMAIL,
    LI.TOTAL_CALLS_COUNT,
    LI.TOTAL_MEETINGS_COUNT,
    LI.TOTAL_EMAILS_COUNT,
    LI.LAST_INTERACTION_DATE,
    COALESCE(ESC.OPEN_ESCALATION_COUNT, 0) AS OPEN_ESCALATION_COUNT,
    VR.NEXT_PLANNED_VISIT_DATE,
    FB.AVERAGE_FEEDBACK_RATING
FROM CLIENT_MASTER C
LEFT JOIN CURRENT_MAPPING CM ON CM.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN RM_MASTER RM ON RM.RM_CODE = CM.RM_CODE
LEFT JOIN LATEST_INTERACTION LI ON LI.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN ESCALATION_ROLLUP ESC ON ESC.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN VISIT_ROLLUP VR ON VR.APR_CLIENT_CODE = C.APR_CLIENT_CODE
LEFT JOIN FEEDBACK_ROLLUP FB ON FB.APR_CLIENT_CODE = C.APR_CLIENT_CODE;
